apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parva.fullname" . }}-secrets
  labels:
    {{- include "parva.labels" . | nindent 4 }}
type: Opaque
stringData:
  PARVA_POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  PARVA_POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  PARVA_MINIO_ACCESS_KEY: {{ .Values.minio.auth.accessKey }}
  PARVA_MINIO_SECRET_KEY: {{ .Values.minio.auth.secretKey }}
  PARVA_LITELLM_API_KEY: {{ .Values.litellm.apiKey }}
